import * as Parser from '../parser/json5Parser';
import * as SchemaService from './json5SchemaService';
import { JSON5WorkerContribution } from '../json5Contributions';
import { PromiseConstructor, Thenable, ClientCapabilities, TextDocument, CompletionItem, CompletionList, Position } from '../json5LanguageTypes';
export declare class JSON5Completion {
    private schemaService;
    private contributions;
    private promiseConstructor;
    private clientCapabilities;
    private supportsMarkdown;
    private supportsCommitCharacters;
    constructor(schemaService: SchemaService.IJSON5SchemaService, contributions?: JSON5WorkerContribution[], promiseConstructor?: PromiseConstructor, clientCapabilities?: ClientCapabilities);
    doResolve(item: CompletionItem): Thenable<CompletionItem>;
    doComplete(document: TextDocument, position: Position, doc: Parser.JSON5Document): Thenable<CompletionList>;
    private getPropertyCompletions;
    private getSchemaLessPropertyCompletions;
    private getSchemaLessValueCompletions;
    private getValueCompletions;
    private getContributedValueCompletions;
    private addSchemaValueCompletions;
    private addDefaultValueCompletions;
    private addEnumValueCompletions;
    private collectTypes;
    private addFillerValueCompletions;
    private addBooleanValueCompletion;
    private addNullValueCompletion;
    private addDollarSchemaCompletions;
    private getLabelForValue;
    private getFilterTextForValue;
    private getFilterTextForSnippetValue;
    private getLabelForSnippetValue;
    private getInsertTextForPlainText;
    private getInsertTextForValue;
    private getInsertTextForSnippetValue;
    private getInsertTextForGuessedValue;
    private getSuggestionKind;
    private getLabelTextForMatchingNode;
    private getInsertTextForMatchingNode;
    private getInsertTextForProperty;
    private getCurrentWord;
    private evaluateSeparatorAfter;
    private findItemAtOffset;
    private isInComment;
    private fromMarkup;
    private doesSupportMarkdown;
    private doesSupportsCommitCharacters;
}
